guest/urls.py
from django.conf.urls import patterns, url
from guest import views, ajax

urlpatterns = patterns('',
    url(r'^$', views.index, name='guest'),
    url(r'^search/$', ajax.searchGuest),
    url(r'^import_guest/', views.importGuest, name='import_guest'),
    url(r'^cleanCI_guest/', views.cleanGuestDocument, name='cleanCI_guest'),
)

urls.py
# linea de comentario
from django.conf import settings
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template

from django.contrib import admin
admin.autodiscover()

from pinax.apps.account.openid_consumer import PinaxConsumer


handler500 = "pinax.views.server_error"


urlpatterns = patterns("",
#    url(r"^$", direct_to_template, {
#        "template": "homepage.html",
#    }, name="home"),
    url(r"^$", "pinax.apps.account.views.login", name="home"),
    url(r"^admin/invite_user/$", "pinax.apps.signup_codes.views.admin_invite_user", name="admin_invite_user"),
    url(r"^admin/", include(admin.site.urls)),
    url(r"^staff/", include("staff.urls")),
    url(r"^about/", include("about.urls")),
    url(r"^account/", include("pinax.apps.account.urls")),
    url(r"^openid/", include(PinaxConsumer().urls)),
#    url(r"^avatar/", include('avatar.urls')),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    url(r'^admin/jsi18n/$', 'django.views.i18n.javascript_catalog'),
)


if settings.SERVE_MEDIA:
    urlpatterns += patterns("",
        url(r"", include("staticfiles.urls")),
    )
"""
if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}))
"""

guest/models.py
from django.db import models
from django.utils.translation import ugettext as _

from utils.utils import DOCUMENT_CHOICES, ISSUE_CHOICES, GENDER_CHOICES
from staff.models import Employee

class Guest(models.Model):
    first_name = models.CharField(verbose_name=_('first_name'), max_length=45)
    last_name = models.CharField(verbose_name=_('last_name'), max_length=45)
    date_created = models.DateField(auto_now_add=True)
    type_document = models.CharField(max_length=5, choices=DOCUMENT_CHOICES)
    issue_document = models.CharField(verbose_name=_('issue_document'),
                                      max_length=3, 
                                      choices=ISSUE_CHOICES,
                                      blank=True,
                                      null=True)
    val_document = models.CharField(verbose_name=_('val_document'),
                                    max_length=30, unique=True)
    gender = models.CharField(verbose_name=_('gender'),
                              max_length=1,
                              choices=GENDER_CHOICES)
    observation = models.CharField(max_length=300, blank=True, null=True)

    def __unicode__(self):
        return self.first_name + ' ' + self.last_name

    def full_name(self):
        return self.first_name + ' ' + self.last_name

    def get_document(self):
        return self.val_document + ' ' + self.issue_document

class BlockGuest(models.Model):
    guest = models.ForeignKey(Guest)
    description = models.CharField(max_length=450)
    date = models.DateTimeField()
    unlock = models.BooleanField(default=False)
    who_unlock = models.ForeignKey(Employee)

guest/views.py
from django.shortcuts import render
from django.conf import settings
from django.db import IntegrityError

from .models import Guest
from register.models import GuestRegistration
from branchoffice.models import BranchOffice

import datetime
import openpyxl

def index(request):
    return render(request, 'guest.html')

def cleanGuestDocument(request):
    guests = Guest.objects.all()
    for guest in guests:
        try:
            vd = guest.val_document
            val = vd.split('.')[0]
            guest.val_document = val
            guest.save()
        except IntegrityError:
            guest.delete()

def importGuest(request):
    workbook = openpyxl.load_workbook(filename = settings.MEDIA_ROOT + '/'
                                      + settings.UPLOAD_PATH
                                      + '/files/registro_personas.xlsx',
                                      use_iterators = True)

    worksheet = workbook.get_sheet_by_name('registros')

    for row in worksheet.iter_rows():
        data = {
                'ci': str(row[0].value).split('.')[0],
                'nombre': row[1].value,
                'apellido': row[2].value,
                'ciudad': row[3].value,
                'sexo': row[4].value,
                'fecha': datetime.datetime.strptime((row[5].value), '%d/%m/%Y').date(),
                'entrada': row[6].value,
                'salida': row[7].value,
                'motivo': row[8].value,
        }
        loadInDBregister(request, data)
    print 'done.html'

def loadInDBregister(request, datalist):
    try:
        guest = Guest.objects.get(val_document=datalist['ci'])
    except Guest.DoesNotExist:
        guest = Guest(first_name=datalist['nombre'],
                    last_name=datalist['apellido'],
                    date_created=datalist['fecha'],
                    type_document='CI',
                    issue_document=datalist['ciudad'],
                    val_document=datalist['ci'],
                    gender='H' if datalist['sexo'] == 'M' else 'M')
        guest.save()

    muyurina = BranchOffice.objects.get(name='Muyurina')
    gr = GuestRegistration(guest=guest,
                           register_date=str(datalist['fecha']),
                           time_entry=str(datalist['fecha']) + ' ' + datalist['entrada'],
                           time_out=str(datalist['fecha']) + ' ' + datalist['salida'],
                           reason=datalist['motivo'],
                           branchoffice=muyurina,
                           owner=request.user)
    gr.save()

guest/templates/ajax_complete_form.html
{% if guest %}
  <div class="form-group alert fade in alert-info">
    {% if guest.gender == 'M' %}
      <b>Bienvenida</b> {{ guest }}
    {% else %}
      <b>Bienvenido</b> {{ guest }}
    {% endif %}
  </div>
{% else %}
  <div class="form-group alert fade in alert-info">
    <h4 align="center">Complete los datos de la persona</h4>
    <div class="form-group">
      <label for="id_subject">Tipo de Documento:</label>
      <select id="id_type_document" class="form-control" name="type_document">
        <option value="CI">Carne de identidad</option>
        <option value="CIE">C.I. extranjero</option>
        <option value="PSP">Pasaporte</option>
        <option value="LM">Libreta militar</option>
        <option value="OTR">Otros</option>
      </select>
    </div>
    <div class="form-group">
      <label for="id_subject">Expedido:</label>
      <select name="city" id="id_city" class="form-control">
        <option value="cba">Cochabamba</option>
        <option value="lpz">La Paz</option>
        <option value="scz">Santa Cruz</option>
        <option value="pnd">Pando</option>
        <option value="ben">Beni</option>
        <option value="oru">Oruro</option>
        <option value="pts">Potosi</option>
        <option value="tja">Tarija</option>
        <option value="scr">Chuquisaca</option>
        <option value="---">Otro</option>
      </select>
    </div>
    <div class="form-group">
      <label for="id_subject">Sexo:</label>
      <select name="gender" id="id_gender" class="form-control">
        <option value="H">Hombre</option>
        <option value="M">Mujer</option>
      </select>
    </div>
    <div class="form-group">
      <label for="id_subject">Nombre:</label>
      <input type="text" name="first_name" id="id_first_name"
             class="form-control" required="True" />
    </div>
    <div class="form-group">
      <label for="id_subject">Apellido:</label>
      <input type="text" name="last_name" id="id_last_name"
             class="form-control" required="True" />
    </div>
  </div>
{% endif %}

guest/templates/guest.html
{% extends 'base.html' %}

{% block content %}
  <h2>Registro de personas</h2>
  <a href="{% url 'import_guest' %}">Importar personas</a>
  <a href="{% url 'cleanCI_guest' %}">Limpiar documentos</a>
{% endblock %}