apps/staff/urls.py
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template
from django.conf.urls.static import static
#import settings, os

urlpatterns = patterns("",
    url(r"^$", "flo.apps.staff.views.staff", name="staff"),
    url(r"^form/", "flo.apps.staff.views.register", name="register"),
    url(r"^(?P<staff_id>\d+)/driver/$", "flo.apps.staff.views.register_driver", name="driver"),
    url(r"^unit/", "flo.apps.staff.views.create_unit", name="create_unit"),
    url(r"^role/", "flo.apps.staff.views.create_role", name="create_role"),
    url(r"^list/", "flo.apps.staff.views.listing", name="listing"),
#    url(r'^media/(?P<path>.*)$', "django.views.static.serve", {'document_root': os.path.join(settings.MEDIA_ROOT, 'site_media')}),
    #url(r"^$", direct_to_template, {"template": "staff/register.html"}, name="register"),
) #+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

"""
import os
urlpatterns += patterns('',
        (r'^site_media/media/(.*)$', 'django.views.static.serve', {'document_root': os.path.join(os.path.abspath(os.path.dirname(__file__)), 'site_media/media')}),
)
"""
"""
if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}))
"""

register/urls.py
from django.conf.urls import patterns, url
from register import views, ajax

urlpatterns = patterns('',
    url(r'^$', views.index, name='register'),
    url(r'^guest_form/', views.registerGuest, name='guest_form'),
    url(r'^guests/today/', views.listGuestsToday, name='list_today_guests'),
    url(r'^guests/withoutexit/', views.listGuestsWithoutExit, name='list_guests_without_exit'),
    url(r'^guests/', views.list_guests, name='list_guests'),
    url(r"^guest/(?P<register_id>\d+)/stop/$", views.stop_guest, name="stop_guest"),
    url(r"^(?P<register_id>\d+)/edit/$", views.editRegisterCar, name="edit_register_car"),
    url(r"^(?P<register_id>\d+)/detail/$", views.detailRegisterCar, name="detail_register_car"),
    url(r"^(?P<register_id>\d+)/view/both/$", views.viewCompleteRegisterCar, name="view_complete_register_car"),
    url(r"^(?P<register_id>\d+)/view/$", views.viewRegisterCar, name="view_register_car"),
    url(r"^(?P<register_id>\d+)/select/workshop/$", views.selectByRegisterWorkshop, name="register_select_workshop"),
    url(r"^search/car/$", views.searchByCar, name="search_by_car"),
    url(r"^search/driver/$", views.searchByDriver, name="search_by_driver"),
    url(r"^search/ladder/$", views.searchByLadder, name="search_by_ladder"),
    url(r"^search/event/car/$", views.searchByCarAndEvent, name="search_by_car_event"),
    url(r"^search/event/driver/$", views.searchByDriverAndEvent, name="search_by_driver_event"),
    url(r"^search/event/ladder/$", views.searchByLadderAndEvent, name="search_by_ladder_event"),
    url(r"^search/guest/$", views.searchByGuest, name="search_by_guest"),
    url(r"^search/guest_ci/$", views.searchByCI, name="search_by_guest_ci"),
#    url(r'^edit/(?P<pk>\d+)/$', views.CarRegistrationUpdate.as_view(), name='car_registration_edit'),
    url(r'^register_form/', views.registerCar, name='form_register_car'),
    url(r'^foreign_register_form/', views.registerForeignCar, name='form_foreign_register_car'),
    url(r'^last/cars/', views.lastRegisters, name='last_registers'),
    url(r'^registers_day/', views.registers_day, name='registers_day'),
    url(r'^registers_all/', views.registers_all, name='registers_all'),
    url(r'^registers_input/', views.registersInput, name='registers_input'),
    url(r'^registers_output/', views.registersOutput, name='registers_output'),
    url(r'^registers_both/', views.registersBoth, name='registers_both'),
    url(r'^mregister_form/', views.registerSimplifiedCar, name='form_register_simplified_car'),
    # Ajax Functions
    url(r'^ajax_validation_car/', ajax.validation_car, name='ajax_validation_car'),
    url(r'^ajax_sidebar/', ajax.validation_car_sidebar, name='ajax_sidebar'),
    url(r'^ajax_delete_date_session/', ajax.delete_date_session, name='ajax_delete_date_session'),
)

staff/urls.py
from django.conf.urls import patterns, url
from staff import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='staff'),
    url(r'^search/name/', views.searchStaffByName, name='search_by_name_staff'),
    url(r'^employee/', views.listEmployee, name='staff_comteco'),
    url(r'^only_staff/', views.onlyStaff, name='only_staff'),
    url(r'^motorist/$', views.getMotorist, name='motorist_comteco'),
    url(r'^motorist/(?P<motorist_id>\d+)/update/$', views.updateMotorist, name='update_motorist'),
    url(r'^search/motorist/item/', views.searchMotoristByItem, name='search_motorist_by_item'),
    url(r'^search/motorist/name/', views.searchMotoristByName, name='search_motorist_by_name_employee'),
    #url(r'^all/', views.EmployeeWorkUnitListView.as_view(), name='staff_all'),
    url(r'^add_staff/', views.addStaff, name='add_staff'),
    url(r"^(?P<staff_id>\d+)/edit/$", views.editStaff, name="edit_staff"),
    url(r"^(?P<staff_id>\d+)/detail/$", views.detailStaff, name="detail_staff"),
    url(r"^(?P<staff_id>\d+)/enabled/$", views.enableDisableStaff, name="enabled_staff"),
    url(r"^(?P<staff_id>\d+)/disabled/$", views.enableDisableStaff, name="disabled_staff"),
    url(r"^(?P<staff_id>\d+)/create_user/$", views.addUser, name="add_user"),
    url(r"^(?P<staff_id>\d+)/create_employee/$", views.addEmployee, name="add_employee"),
    url(r"^(?P<staff_id>\d+)/create_guard/$", views.addGuard, name="add_guard"),
    url(r"^(?P<staff_id>\d+)/profile/$", views.viewProfile, name="view_profile_staff"),
    url(r"^employee/(?P<employee_id>\d+)/detail/$", views.detailEmployee, name="detail_employee"),
    url(r'^upload_staff', views.uploadStaff, name='upload_staff'),
    url(r'^upload_driver', views.uploadDriver, name='upload_driver'),
    url(r'^search/item/', views.searchByItem, name='search_by_item'),
    url(r'^search/employee/name/', views.searchEmployeeByName, name='search_by_name_employee'),
)

urls.py
# linea de comentario
from django.conf import settings
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template

from django.contrib import admin
admin.autodiscover()

from pinax.apps.account.openid_consumer import PinaxConsumer


handler500 = "pinax.views.server_error"


urlpatterns = patterns("",
#    url(r"^$", direct_to_template, {
#        "template": "homepage.html",
#    }, name="home"),
    url(r"^$", "pinax.apps.account.views.login", name="home"),
    url(r"^admin/invite_user/$", "pinax.apps.signup_codes.views.admin_invite_user", name="admin_invite_user"),
    url(r"^admin/", include(admin.site.urls)),
    url(r"^staff/", include("staff.urls")),
    url(r"^about/", include("about.urls")),
    url(r"^account/", include("pinax.apps.account.urls")),
    url(r"^openid/", include(PinaxConsumer().urls)),
#    url(r"^avatar/", include('avatar.urls')),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    url(r'^admin/jsi18n/$', 'django.views.i18n.javascript_catalog'),
)


if settings.SERVE_MEDIA:
    urlpatterns += patterns("",
        url(r"", include("staticfiles.urls")),
    )
"""
if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}))
"""

register/models.py
from django.db import models

from staff.models import Employee
from guest.models import Guest
from branchoffice.models import Car, BranchOffice, Ladder
from core.models import User

from django.utils.translation import gettext_lazy as _

class CarRegistration(models.Model):
    EVENT_CHOICES = (
            ('entrada', _('input')),
            ('salida', _('output')),
    )

    employee = models.ForeignKey(Employee, blank=True, null=True)
    guest = models.ForeignKey(Guest, blank=True, null=True)
    car = models.ForeignKey(Car)
    branch_office = models.ForeignKey(BranchOffice)
    register_date = models.DateField()
    register_time = models.DateTimeField()
    register_km = models.IntegerField()
    ladders = models.CharField(max_length=50, blank=True, null=True)
    date_modification = models.DateTimeField()
    event = models.CharField(max_length=10, choices=EVENT_CHOICES)
    owner = models.ForeignKey(User)
    observation = models.CharField(max_length=450, blank=True, null=True)

    class Meta:
        permissions = (
            ('view_register', 'Puede ver el detalle de registro'),
        )

    def __unicode__(self):
        return 'id_reg: ' + str(self.id) + ' car: ' + str(self.car)

    def get_absolute_url(self):
        return '/register/%i' % self.id

    def get_date_str(self):
        return self.register_date.strftime("%d/%m/%y")

class AllCarRegistration(models.Model):
    car = models.ForeignKey(Car)
    custody_out = models.ForeignKey(Employee, related_name='custody_out',
                                    blank=True, null=True)
    custody_in = models.ForeignKey(Employee, related_name='custody_in',
                                   blank=True, null=True)
    other_driver = models.ForeignKey(Guest, blank=True, null=True)
    parking_out = models.ForeignKey(BranchOffice, related_name='parking_out',
                                    blank=True, null=True)
    parking_in = models.ForeignKey(BranchOffice, related_name='parking_in',
                                   blank=True, null=True)
    # register_date: este es la fecha que a sido creado el registro
    register_date = models.DateField()
    time_out = models.DateTimeField(blank=True, null=True)
    km_out = models.IntegerField(blank=True, null=True)
    time_in = models.DateTimeField(blank=True, null=True)
    km_in = models.IntegerField(blank=True, null=True)
    ladders_out = models.CharField(max_length=50, blank=True, null=True)
    ladders_in = models.CharField(max_length=50, blank=True, null=True)
    register_out = models.ForeignKey(CarRegistration,
                                     blank=True, null=True,
                                     related_name='register_out')
    register_in = models.ForeignKey(CarRegistration,
                                    blank=True, null=True,
                                    related_name='register_in')
    # Si el vehiculo no sale is_complete es True
    is_complete = models.BooleanField()

    # True: si el vehiculo no salio de parqueo
    # False: si el vehiculo salio de parqueo
    #in_parking = models.BooleanField(default=False)
    observation = models.CharField(max_length=450, blank=True, null=True)

    #alert: este campo es para senialar que el registro tiene una alerta, puede ser
    # que le ocurrio algun robo, choque, escaleras incompletas. El administrado
    # es el unico que puede quitar esta alerta.
    # Este alert es diferente de is_complete, is_complete solo verifica que el
    # registro tenga hora de salida y llegada.
    # THINKING: se probara usando las notificaciones, antes de habilitar esta
    # opcion.
    #alert = models.BooleanField(default=False)

    def __unicode__(self):
        return str(self.car)

    def diferent_custody(self):
        if self.custody_out != self.custody_in:
            return True
        else:
            return False

    def get_diff_km(self):
        if self.km_in is None or self.km_out is None:
            return '---'
        else:
            return self.km_in - self.km_out

    def get_absolute_url(self):
        return '/register/%i' % self.id

    def get_date_str(self):
        return self.register_date.strftime("%d/%m/%y")

    def get_time_in_str(self):
        if self.time_in is None:
            return '---'
        else:
            return self.time_in.strftime("%H:%M")

    # TODO: Este metodo hay que mejorar, para que haga una mejor comparacion y
    # saber que escalera falta, seria bueno usar expresiones regulares como esta:
    # re.findall(r"[\w]+", cadena), esto devuelve una lista.
    def compareLadders(self):
        if self.ladders_out != self.ladders_in:
            return True
        else:
            return False

class LadderRegistration(models.Model):
    car_register = models.ForeignKey(CarRegistration)
    ladders = models.ForeignKey(Ladder)

class ObservationsRegCar(models.Model):
    car_register = models.ForeignKey(CarRegistration)
    description = models.CharField(max_length=450, blank=True, null=True)
    date_created = models.DateField()

class StatusCar(models.Model):
    car = models.ForeignKey(Car, unique=True)
    last_register_car = models.ForeignKey(CarRegistration,
                                          blank=True, null=True)
    # es True si el estado de last_register_car es 'output' o salida
    in_moving = models.BooleanField(default=False)
    parking = models.ForeignKey(BranchOffice)

    def __unicode__(self):
        return self.car.__unicode__()

    def get_status(self):
        return self.in_moving

    def get_parking(self):
        if self.last_register_car is not None:
            return self.last_register_car.branchoffice
        else:
            return None

    def updateStatus(self, register):
        if self.in_moving:
            self.car.current_km = register.register_km
            self.car.save()
            reg_complete = AllCarRegistration(car=self.last_register_car.car,
                                              custody_out=self.last_register_car.employee,
                                              custody_in=register.employee,
                                              parking_out=self.last_register_car.branch_office,
                                              parking_in=register.branch_office,
                                              register_date=self.last_register_car.register_date,
                                              time_out=self.last_register_car.register_time,
                                              km_out=self.last_register_car.register_km,
                                              ladders_out=self.last_register_car.ladders,
                                              time_in=register.register_time,
                                              km_in=register.register_km,
                                              ladders_in=register.ladders,
                                              register_out=self.last_register_car,
                                              register_in=register,
                                              is_complete=True)
            reg_complete.save()
            self.in_moving = False
            self.last_register_car = register
            self.parking = register.branch_office
            self.save()
        else:
            self.in_moving = True
            self.last_register_car = register
            self.save()

            if self.car.current_km is None:
                self.car.current_km = register.register_km
                self.car.save()

# GuestRegistration: Registra el ingreso de personas a oficinas
class GuestRegistration(models.Model):
    guest = models.ForeignKey(Guest)
    register_date = models.DateField(auto_now_add=True)
    time_entry = models.DateTimeField(auto_now_add=True)
    time_out = models.DateTimeField(blank=True, null=True)
    reason = models.CharField(max_length=450)
    branchoffice = models.ForeignKey(BranchOffice)
    owner = models.ForeignKey(User)

    def get_date_str(self):
        return self.register_date.strftime("%d/%m/%y")

    def get_time_out_str(self):
        if self.time_out is None:
            return '---'
        else:
            return self.time_out.strftime("%H:%M")

# CarsWithNoExits: En esta tabla se registran todos los autos que no tuvieron
# ninguna salida en el dia
class CarsWithNoExits(models.Model):
    car = models.ForeignKey(Car)
    parking = models.ForeignKey(BranchOffice)
    register_date = models.DateField()
    observation = models.CharField(max_length=450)

# CarsCurrentState: nos permite saber cual fue la ultima salida del vehiculo
# y en donde termino
class CarsCurrentState(models.Model):
    car = models.ForeignKey(Car)
    last_parking = models.ForeignKey(BranchOffice)
    last_register = models.ForeignKey(CarRegistration, blank=True, null=True)
    date = models.DateTimeField()
    observation = models.CharField(max_length=450)

# En esta tabla se pretende guardar la fecha de los registros que se estan
# guardando por el guardia de un parqueo.
class LastDateRegisterByBranchoffice(models.Model):
    branchoffice = models.ForeignKey(BranchOffice, unique=True)
    last_date_registers = models.DateField()

# Para los registros temporales, si llega a tener un par, de salida y entrada se
# carga a la tabla AllCarRegistration.
class ForeignCarRegistrationIO(models.Model):
    TYPE_EVENT = (
        ('entrada', 'Entrada'),
        ('salida', 'Salida')
    )

    car = models.ForeignKey(Car)
    parking = models.ForeignKey(BranchOffice)
    register_in = models.ForeignKey(CarRegistration,
                                    related_name='tmp_register_in',
                                    blank=True, null=True)
    register_out = models.ForeignKey(CarRegistration,
                                     related_name='tmp_register_out',
                                     blank=True, null=True)
    # date_modification: es la ultima fecha que ocurrio un evento con este
    # vehiculo.

apps/register/views.py
from django.shortcuts import render_to_response

def register(request):
    return render_to_response('register.html')

templates/staff/driver_reg.html
{% extends "site_base.html" %}

{% load i18n %}
{% load bootstrap_tags %}
{% load ifsetting_tag %}
{% load adminmedia %}
{% block head_title %}{% trans "Registro" %}{% endblock %}

<script type="text/javascript">
    window.__admin_media_prefix__ = "{% filter escapejs %}{% admin_media_prefix %}{% endfilter %}";
</script>


{{ form.media }}
    <script type="text/javascript" src="/admin/jsi18n/"></script>
    <script type="text/javascript" src="/media/admin/js/core.js"></script>
    <link rel="stylesheet" type="text/css" href="/media/admin/css/forms.css"/>
    <link rel="stylesheet" type="text/css" href="/media/admin/css/base.css"/>
    <link rel="stylesheet" type="text/css" href="/media/admin/css/global.css"/>
    <link rel="stylesheet" type="text/css" href="/media/admin/css/widgets.css"/>
{{ form.media }}

{% block body %}
    <h1>{% trans "Datos del conductor" %}</h1>
    
    {% if user.is_authenticated %}
        <form action="/staff/{{staff_id}}/driver/" method="post" class="form-horizontal">
            <fieldset>
                <input type="hidden" value="{{staff_id}}" name="staff">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="form-actions">
                    <button type="submit" class="btn btn-primary">{% trans "Done" %}</button>
                </div>
            </fieldset>
        </form>
    {% else %}
    {% endif %}
{% endblock %}

templates/staff/list.html
{% for staff in staff_list.object_list %}
    {# Each "contact" is a Contact model object. #}
    {{ staff|upper }}<br />
{% endfor %}

<div class="pagination">
    <span class="step-links">
        {% if staff_list.has_previous %}
        <span class="paginate_previous">
            <a class="paginate_previous" href="?page={{ staff_list.previous_page_number }}">previous</a>
        </span>
        {% endif %}

        <span class="current">
            Page {{ staff_list.number }} of {{ staff_list.paginator.num_pages }}.
        </span>

        {% if staff_list.has_next %}
        <span class="paginate_next">
            <a href="?page={{ staff_list.next_page_number }}">next</a>
        </span>
        {% endif %}
    </span>
</div>

templates/staff/register.html
{% extends "subnav_base.html" %}

{% load i18n %}
{% load bootstrap_tags %}
{% load ifsetting_tag %}

{% block head_title %}{% trans "Registro" %}{% endblock %}

{% block subnav%}
    <ul class="nav nav-list">
        <li class="nav-header">{% trans "Options" %}</li>
        <li><a href="{% url staff %}">{% trans "Lista de Personal" %}</a></li>
        <li><a href="{% url create_unit %}">{% trans "Crear Unidad" %}</a></li>
        <li><a href="{% url register %}">{% trans "Registro de Conductores" %}</a></li>
    </ul>
{% endblock %}

{% block body %}
    <h1>{% trans "Formulario de registro del personal" %}</h1>
    
    {% if user.is_authenticated %}
        <form action="{% url register %}" method="post" class="form-horizontal" enctype="multipart/form-data" class="infotabs accfrm">
            <fieldset>
                {% csrf_token %}
                {{ form.as_p }}
                <div class="form-actions">
                    <button type="submit" class="btn btn-primary">{% trans "Siguiente" %}</button>
                </div>
            </fieldset>
        </form>
    {% else %}
    {% endif %}
{% endblock %}

templates/staff/role.html
{% extends "site_base.html" %}

{% load i18n %}
{% load bootstrap_tags %}
{% load ifsetting_tag %}

{% block head_title %}{% trans "Unit" %}{% endblock %}

{% block body %}
    <h1>{% trans "Forumulario para crear roles" %}</h1>
    
    {% if user.is_authenticated %}
        <form action="{% url create_role  %}" method="post" class="form-horizontal">
            <fieldset>
                {% csrf_token %}
                {{ form.as_p }}
                <div class="form-actions">
                    <button type="submit" class="btn btn-primary">{% trans "Done" %}</button>
                </div>
            </fieldset>
        </form>
    {% else %}
    {% endif %}
{% endblock %}

templates/staff/staff.html
{% extends "subnav_base.html" %}

{% load i18n %}
{% load ifsetting_tag %}
{% load pagination_tags %}
{% load staticfiles %}

{% block head_title %}{% trans "Staff" %}{% endblock %}

{% block subnav%}
    <ul class="nav nav-list">
        <li class="nav-header">{% trans "Options" %}</li>
        <li><a href="{% url create_unit %}">{% trans "Crear Unidad" %}</a></li>
        <li><a href="{% url register %}">{% trans "Registro de Conductores" %}</a></li>
    </ul>
{% endblock %}

{% block body %}
    <h1>{% trans "Personal Comteco" %}</h1>
    
    {% if user.is_authenticated %}
        {% autopaginate staff_list 10 %}
        <table class="table">
            {% for staff in staff_list %}
                <tr>
                    {% if staff.avatar != '' %}
                        <td><a href="{{MEDIA_URL}}{{staff.avatar}}"><img src="{{MEDIA_URL}}{{staff.avatar}}" width="40" height="40" alt=""></a></td>
                    {% else %}
                        <td><a href="{{MEDIA_URL}}img/avatar/default.jpg"><img src="{{MEDIA_URL}}img/avatar/default.jpg" width="40" height="40" alt=""></a></td>
                    {% endif %}
                    <td>{{ staff.full_name }}</td>
                </tr>
            {% endfor %}
        </table>
        {% paginate %}
        <p>
        Esta plataforma realiza el control del personal interno y externo, como tambien el control
        de los activos fisicos.
        </p>
        
    {% else %}
        {% url acct_login as login_url %}
        
        <p class="what_next">
            {% blocktrans %}Ingrese sus datos <a href="{{ login_url }}">logging in</a>.{% endblocktrans %}
        </p>
    {% endif %}
{% endblock %}

templates/staff/staff_list.html
{% extends "base.html" %}

{% load i18n %}
{% load staticfiles %}}
{% load pagination_tags %}

{% block content %}
    <!-- a href="{% url "upload_staff" %}">Cargar el personal</a>
    <a href="{% url "upload_driver" %}">Cargar a los conductores de vehiculos</a -->
        <h2>Todo el personal</h2>
    <div class="row">
        <div class="col-xs-4">
            <form method="GET" action="{% url 'search_by_item' %}"
                  class="form-inline" role="form">{% csrf_token %}
                <input type='text' id='id_item' name='item' autocomplete='off'
                  class="form-control" placeholder="Item Empleado" />
                <button type='submit' class="btn btn-default">
                    Buscar
                </button>
            </form>
        </div>
        <div class="col-xs-4">
            <form method="GET" action="{% url 'search_by_name_employee' %}"
                  class="form-inline" role="form">{% csrf_token %}
                <input type='text' id='id_employee' name='employee' autocomplete='off'
                  class="form-control" placeholder="Nombre del Empleado" />
                <button type='submit' class="btn btn-default">
                    Buscar
                </button>
            </form>
        </div>
    </div>
    </br>
    <div class="table-responsive">
        <table class="table">
            <tr>
                <td><b></b></td>
                <td><b>Nombre</b></td>
                <td><b>Fecha de nacimiento</b></td>
            </tr>
            {% autopaginate object_list 15 %}
            {% for staff in object_list %}
                <tr class="active">
                    <td>
                        <img src="{{staff.photo.url_48x48}}" width="48" height="48" alt="" />
                    </td>
                    <td>{{ staff }}</td>
                    <td>{{ staff.birth_date|date:"M d" }}</td>
                </tr>
            {% endfor %}
        </table>
    </div>
{% paginate %}

{% endblock %}

templates/staff/unit.html
{% extends "subnav_base.html" %}

{% load i18n %}
{% load bootstrap_tags %}
{% load ifsetting_tag %}

{% block head_title %}{% trans "Unit" %}{% endblock %}

{% block subnav%}
    <ul class="nav nav-list">
        <li class="nav-header">{% trans "Options" %}</li>
        <li><a href="{% url staff %}">{% trans "Lista de Personal" %}</a></li>
        <li><a href="{% url create_unit %}">{% trans "Crear Unidad" %}</a></li>
        <li><a href="{% url register %}">{% trans "Registro de Conductores" %}</a></li>
    </ul>
{% endblock %}

{% block body %}
    <h1>{% trans "Formulario para crear unidades" %}</h1>
    
    {% if user.is_authenticated %}
        <form action="{% url create_unit  %}" method="post" class="form-horizontal">
            <fieldset>
                {% csrf_token %}
                {{ form.as_p }}
                <div class="form-actions">
                    <button type="submit" class="btn btn-primary">{% trans "Done" %}</button>
                </div>
            </fieldset>
        </form>
    {% else %}
    {% endif %}
{% endblock %}