maintenance/urls.py
from django.conf.urls import patterns, url
from maintenance import views, ajax

urlpatterns = patterns('',
    url(r'^$', views.index, name='maintenance'),
    url(r'^search/$', views.searchWorkshopByCar, name='search_workshop_by_car'),
    url(r'^in_workshop/$', views.inWorkshop, name='in_workshop'),
    url(r'^workshop/list/$', views.workshopList, name='workshop_list'),
    url(r'^workshop/new/$', views.newWorkshop, name='new_workshop'),
    url(r"^workshop/(?P<workshop_id>\d+)/cars/$", views.carsInWorkshop),
    url(r"^workshop/(?P<workshop_id>\d+)/disabled/$", views.onOffWorkshop),
    url(r"^workshop/(?P<workshop_id>\d+)/enabled/$", views.onOffWorkshop),
    url(r'^program/$', views.maintenanceProgram, name='maintenance_program'),
    url(r'^program/form/$', views.maintenanceProgramCar, name='form_maintenance_program'),
    url(r"^program/(?P<mp_id>\d+)/close/$", views.maintenanceProgramClose, name="close_maintenance"),
    url(r"^program/(?P<mp_id>\d+)/open/$", views.maintenanceProgramClose, name="close_maintenance"),
    url(r'^program/search/$', views.searchMaintenanceProgramByCar, name='search_maintenance_program'),
    url(r'^program/ajax_sidebar/$', ajax.lastMaintenance, name='last_maintenance'),
    url(r"^in/workshop/(?P<maintenance_id>\d+)/view/$", views.viewCarInWorkshop, name="view_car_workshop"),
    url(r"^in/workshop/(?P<maintenance_id>\d+)/fixed/$", views.fixedCar, name="fixed_car_workshop"),
)

urls.py
# linea de comentario
from django.conf import settings
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template

from django.contrib import admin
admin.autodiscover()

from pinax.apps.account.openid_consumer import PinaxConsumer


handler500 = "pinax.views.server_error"


urlpatterns = patterns("",
#    url(r"^$", direct_to_template, {
#        "template": "homepage.html",
#    }, name="home"),
    url(r"^$", "pinax.apps.account.views.login", name="home"),
    url(r"^admin/invite_user/$", "pinax.apps.signup_codes.views.admin_invite_user", name="admin_invite_user"),
    url(r"^admin/", include(admin.site.urls)),
    url(r"^staff/", include("staff.urls")),
    url(r"^about/", include("about.urls")),
    url(r"^account/", include("pinax.apps.account.urls")),
    url(r"^openid/", include(PinaxConsumer().urls)),
#    url(r"^avatar/", include('avatar.urls')),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    url(r'^admin/jsi18n/$', 'django.views.i18n.javascript_catalog'),
)


if settings.SERVE_MEDIA:
    urlpatterns += patterns("",
        url(r"", include("staticfiles.urls")),
    )
"""
if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}))
"""

maintenance/models.py
from django.db import models

from branchoffice.models import Car
from register.models import CarRegistration
from branchoffice.models import BranchOffice

class Workshop(models.Model):
    branchoffice = models.ForeignKey(BranchOffice)
    description = models.CharField(max_length=450)
    is_active = models.BooleanField(default=True)

    def __unicode__(self):
        return self.branchoffice.name

    def get_absolute_url(self):
        return '/maintenance/workshop/%i' % self.id


class MaintenanceWorkshop(models.Model):
    workshop = models.ForeignKey(Workshop)
    car = models.ForeignKey(Car)
    register = models.ForeignKey(CarRegistration)
    date_joined = models.DateField()
    date_out = models.DateField(blank=True, null=True)
    problem_description = models.CharField(max_length=450)
    fixed = models.BooleanField()
#    service = models.ManyToManyField(MaintenanceProgram, through='ServiceCar')

    def __unicode__(self):
        return str(self.car)

    def get_absolute_url(self):
        return '/maintenance/in/workshop/%i' % self.id

    def get_date_joined_str(self):
        return self.date_joined.strftime("%d/%m/%y")

    def get_date_out_str(self):
        if self.date_out is None:
            return '---'
        else:
            return self.date_out.strftime("%d/%m/%y")

#class ServiceCar(models.Model)

class MaintenanceProgram(models.Model):
    car = models.ForeignKey(Car)
    workshop = models.ForeignKey(Workshop)
    last_maintenance = models.ForeignKey(MaintenanceWorkshop,
                                         blank=True, null=True)
    last_km_maintenance = models.IntegerField(blank=True, null=True)
    last_date_maintenance = models.DateField(blank=True, null=True)
    next_km_maintenance = models.IntegerField(blank=True, null=True)
    next_date_maintenance = models.DateField(blank=True, null=True)
    date_asigned = models.DateField()
    date_closed = models.DateField(blank=True, null=True)
    reason = models.CharField(max_length=450, blank=True, null=True)
    is_closed = models.BooleanField(default=False)

    def __unicode__(self):
        return str(self.car)

    def get_absolute_url(self):
        return '/maintenance/program/%i' % self.id


class MaintenanceCar(models.Model):
    car = models.ForeignKey(Car)
    km_interval_maintenance = models.IntegerField()
    km_last_maintenance = models.IntegerField()
    date_last_maintenance = models.DateField()
    next_km_maintenance = models.IntegerField()

maintenance/forms.py
from django import forms
from bootstrap3_datetime.widgets import DateTimePicker

from branchoffice.models import Car
from maintenance.models import Workshop

import datetime

class FormMaintenanceProgram(forms.Form):
    workshop = forms.ModelChoiceField(queryset=Workshop.objects.filter(is_active=True),
                                      widget=forms.Select(attrs={'class': 'form-control'}),
                                      initial=0)
    internal_number = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control',
                                                                    'placeholder': 'Interno del Vehiculo',
                                                                    'onchange': 'maintenance_car()',
                                                                    'autofocus':''}))
    next_km_maintenance = forms.IntegerField(widget=forms.TextInput(attrs={'class': 'form-control',
                                                                           'placeholder': 'Kilometraje'}),
                                             required=False)
    next_date_maintenance = forms.DateField(widget=DateTimePicker(options={"format":"DD/MM/YYYY", "pickTime": False}))
    reason = forms.CharField(widget=forms.Textarea(attrs={'rows': '3',
                                                          'class': 'form-control',
                                                          'placeholder': 'Motivo del mantenimiento'}),
                             required=False)

    def clean(self):
        cleaned_data = self.cleaned_data
        internal_number = self.cleaned_data.get('internal_number')
        km = self.cleaned_data.get('next_km_maintenance')
        try:
            car = Car.objects.get(internal_number=internal_number)
        except Car.DoesNotExist:
            raise forms.ValidationError('El Vehiculo no existe')
        if car.current_km:
            if km < car.current_km:
                raise forms.ValidationError('El Kilometraje es menor que su km actual.')
            else:
                return cleaned_data
        else:
            return cleaned_data

    def clean_internal_number(self):
        internal_number = self.cleaned_data['internal_number']
        try:
            car = Car.objects.get(internal_number=internal_number)
            return car.internal_number
        except Car.DoesNotExist:
            return forms.ValidationError('El interno del Vehiculo no existe')

    def clean_next_date_maintenance(self):
        next_date_maintenance = self.cleaned_data['next_date_maintenance']
        if next_date_maintenance < datetime.date.today():
            raise forms.ValidationError('La fecha debe ser mayor la de hoy')
        else:
            return next_date_maintenance

class FormWorkshop(forms.ModelForm):
    class Meta:
        model = Workshop
        widgets = {
                'branchoffice': forms.Select(attrs={'class': 'form-control',
                                                    'autofocus': ''}),
                'description': forms.Textarea(attrs={'rows': '3',
                                                     'class': 'form-control',
                                                     'placeholder': 'Ingrese alguna descripcion'})
        }

    def clean_branchoffice(self):
        branchoffice = self.cleaned_data['branchoffice']
        try:
            bo = Workshop.objects.get(branchoffice=branchoffice)
            raise forms.ValidationError('El taller %s ya existe' % bo.branchoffice)
        except Workshop.DoesNotExist:
            return branchoffice

maintenance/views.py
from django.shortcuts import render, render_to_response
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.template import RequestContext

from maintenance.models import (MaintenanceWorkshop,
                                MaintenanceProgram,
                                Workshop)
from maintenance.forms import FormMaintenanceProgram, FormWorkshop
from branchoffice.models import Car

import datetime

@login_required
def index(request):
    m_all = MaintenanceWorkshop.objects.all().order_by('-date_joined')
    return render(request,
                  'maintenance.html',
                  {'m_list': m_all})

@login_required
def inWorkshop(request):
    m_all = MaintenanceWorkshop.objects.filter(fixed=False)
    return render(request,
                  'maintenance.html',
                  {'m_list': m_all})

@login_required
def viewCarInWorkshop(request, maintenance_id):
    m_car = MaintenanceWorkshop.objects.get(id=maintenance_id)
    return render(request,
                  'view_car_workshop.html',
                  {'workshop': m_car})

@login_required
def fixedCar(request, maintenance_id):
    m_car = MaintenanceWorkshop.objects.get(id=maintenance_id)
    m_car.date_out = datetime.date.today()
    m_car.fixed = True
    m_car.save()
    m_car.car.is_active = True
    m_car.car.save()
    return HttpResponseRedirect('/maintenance/')

@login_required
def maintenanceProgramClose(request, mp_id):
    mp = MaintenanceProgram.objects.get(id=mp_id)
    if not mp.is_closed:
        mp.is_closed = True
        mp.date_closed = datetime.date.today()
        mp.save()
        messages.add_message(request,
                             messages.SUCCESS,
                             'Se cancelo el mantenimiento para: ' + mp.car.internal_number)
    else:
        if mp.next_date_maintenance > datetime.date.today():
            mp.is_closed = False
            mp.date_closed = None
            mp.save()
            messages.add_message(request,
                                messages.SUCCESS,
                                'Se habilito el mantenimiento para: ' + mp.car.internal_number)

    return HttpResponseRedirect('/maintenance/program/')

@login_required
def searchWorkshopByCar(request):
    if request.method == 'GET':
        try:
            internal_number = request.GET['car']
            car = Car.objects.get(internal_number=internal_number)
            ws = MaintenanceWorkshop.objects.filter(car=car).order_by('-date_joined')
            if not ws:
                messages.add_message(request,
                                     messages.WARNING,
                                     'No se encontro ningun ingreso.')
            return render(request,
                        'maintenance.html',
                        {'m_list': ws})
        except Car.DoesNotExist:
            messages.add_message(request,
                                 messages.ERROR,
                                 'El interno de vehiculo no existe.')
            return HttpResponseRedirect('/maintenance/')

@login_required
def searchMaintenanceProgramByCar(request):
    if request.method == 'GET':
        try:
            internal_number = request.GET['car']
            car = Car.objects.get(internal_number=internal_number)
            mp = MaintenanceProgram.objects.filter(car=car).order_by('-next_date_maintenance')
            if not mp:
                messages.add_message(request,
                                     messages.WARNING,
                                     'No se encontro ningun ingreso.')
            return render(request,
                        'maintenance_program.html',
                        {'mp_list': mp})
        except Car.DoesNotExist:
            messages.add_message(request,
                                 messages.ERROR,
                                 'El interno de vehiculo no existe.')
            return HttpResponseRedirect('/maintenance/program/')

@login_required
def maintenanceProgram(request):
    mp = MaintenanceProgram.objects.all()
    return render(request,
                  'maintenance_program.html',
                  {'mp_list': mp})

@login_required
def maintenanceProgramCar(request):
    if request.method == 'POST':
        form = FormMaintenanceProgram(request.POST)
        if form.is_valid():
            workshop = form.cleaned_data['workshop']
            internal_number = form.cleaned_data['internal_number']
            next_km_maintenance = form.cleaned_data['next_km_maintenance']
            next_date_maintenance = form.cleaned_data['next_date_maintenance']
            reason = form.cleaned_data['reason']

            car = Car.objects.get(internal_number=internal_number)
            lm = MaintenanceWorkshop.objects.filter(car=car).filter(fixed=True).order_by('-date_out')
            if lm:
                lm = lm[0]
                pm = MaintenanceProgram(car=car,
                                        workshop=workshop,
                                        last_maintenance=lm,
                                        last_km_maintenance=lm.register.register_km,
                                        last_date_maintenance=lm.date_out,
                                        next_km_maintenance=next_km_maintenance,
                                        next_date_maintenance=next_date_maintenance,
                                        reason=reason,
                                        date_asigned=datetime.date.today())
                pm.save()

            else:
                pm = MaintenanceProgram(car=car,
                                        workshop=workshop,
                                        next_km_maintenance=next_km_maintenance,
                                        next_date_maintenance=next_date_maintenance,
                                        reason=reason,
                                        date_asigned=datetime.date.today())
                pm.save()

            messages.add_message(request,
                                messages.SUCCESS,
                                'Se guardo satisfactoriamente para el vehiculo %s ' % car)
            return HttpResponseRedirect('/maintenance/program/')
        else:
            messages.add_message(request,
                                messages.ERROR,
                                'Los datos ingresados son incorrectos.')
            return render_to_response('form_program_maintenance.html', {'form': form},
                                      context_instance=RequestContext(request))
    else:
        form = FormMaintenanceProgram()
        return render_to_response('form_program_maintenance.html', {'form': form},
                                    context_instance=RequestContext(request))

@login_required
def newWorkshop(request):
    if request.method == 'POST':
        form = FormWorkshop(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/maintenance/')
        else:
            messages.add_message(request,
                                messages.ERROR,
                                'Los datos ingresados son incorrectos.')
            return render_to_response('form_workshop.html', {'form': form},
                                      context_instance=RequestContext(request))
    else:
        form = FormWorkshop()
        return render_to_response('form_workshop.html', {'form': form},
                                  context_instance=RequestContext(request))

@login_required
def workshopList(request):
    wl = Workshop.objects.all()
    return render(request,
                  'workshop.html',
                  {'w_list': wl})

@login_required
def carsInWorkshop(request, workshop_id):
    workshop = Workshop.objects.get(id=workshop_id)
    mw = MaintenanceWorkshop.objects.filter(workshop=workshop)
    return render(request,
                  'maintenance.html',
                  {'m_list': mw})

@login_required
def onOffWorkshop(request, workshop_id):
    workshop = Workshop.objects.get(id=workshop_id)
    if workshop.is_active:
        workshop.is_active = False
        workshop.save()
    else:
        workshop.is_active = True
        workshop.save()
    return HttpResponseRedirect('/maintenance/workshop/list/')

maintenance/templates/form_program_maintenance.html
{% extends "subnav_base.html" %}

{% load i18n %}
{% load staticfiles %}}

{% block sidebar %}
{% endblock %}


{% block navbar_right %}
    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        Opciones <span class="caret"></span>
        </a>
        <ul class="dropdown-menu" role="menu">
            <li>
                <a href="{% url 'new_workshop' %}">
                <span>{% trans 'Asignar nuevo taller'%}</span>
                </a>
            </li>
        </ul>
    </li>
{% endblock %}

{% block main-content %}
  <form action="{% url 'form_maintenance_program' %}" method="post">{% csrf_token %}
    {{ form.non_field_errors }}
    <div class="form-group">
      {{ form.workshop.errors }}
      <label for="id_subject">Taller:</label>
      {{ form.workshop }}
    </div>
    <div class="form-group">
      {{ form.internal_number.errors }}
      <label for="id_subject">Interno del vehiculo:</label>
      {{ form.internal_number }}
    </div>
    <div class="form-group">
      {{ form.next_km_maintenance.errors }}
      <label for="id_subject">Kilometraje limite para mantenimiento:</label>
      {{ form.next_km_maintenance }}
    </div>
    <div class="form-group">
        {{ form.next_date_maintenance.errors }}
        <label for="id_subject">Fecha para el mantenimiento:</label>
        {{ form.next_date_maintenance }}
    </div>
    <div class="form-group">
      {{ form.reason.errors }}
      <label for="id_subject">Motivo:</label>
      {{ form.reason }}
    </div>
    <input type="submit" value="Guardar" class="btn btn-primary"/>
</form>
{% endblock%}

maintenance/templates/form_workshop.html
{% extends "subnav_base.html" %}

{% load i18n %}
{% load staticfiles %}}

{% block sidebar %}
{% endblock %}


{% block navbar_right %}
{% endblock %}

{% block main-content %}
<h4>Formulario para asignar un nuevo Taller</h4>
  <form action="{% url 'new_workshop' %}" method="post">{% csrf_token %}
    {{ form.non_field_errors }}
    <div class="form-group">
      {{ form.branchoffice.errors }}
      <label for="id_subject">Oficina:</label>
      {{ form.branchoffice }}
    </div>
    <div class="form-group">
      {{ form.description.errors }}
      <label for="id_subject">Descripcion:</label>
      {{ form.description }}
    </div>
    <input type="submit" value="Guardar" class="btn btn-primary"/>
</form>
{% endblock%}

maintenance/templates/last_maintenance.html
<div class="alert fade in alert-info">
  <b>Fecha del ultimo mantenimiento:</b>
  {{ last_maintenance.date_out|date:"d/m/Y" }}</br>
  <b>Kilometraje:</b> {{ last_maintenance.register.register_km }}</br>
  <b>Chofer que ingreso</b>
  <div align="center">
    <img src="{{last_maintenance.register.employee.staff.photo.url_90x90}}" width="90" height="90" alt="">
  </div>
  {{ last_maintenance.register.employee }}</br>
  <b>Item:</b> {{ last_maintenance.register.employee.item }}</br>
  <b>Kilometraje Actual:</b> {{ car.current_km }}
</div>

maintenance/templates/maintenance.html
{% extends "base.html" %}

{% load i18n %}
{% load staticfiles %}}
{% load pagination_tags %}


{% block content %}
<h4>Vehiculos en Taller</h4>
<div class="row">
    <div class="col-xs-4">
        <form method="GET"
                action="{% url 'search_workshop_by_car' %}" 
                class="form-inline" role="form">{% csrf_token %}
            <input type='text'
                    id='id_car' name='car'
                    autocomplete='off'
                    class="form-control" placeholder="Interno de Vehiculo" />
            <button type='submit' class="btn btn-default">
                Buscar
            </button>
        </form>
    </div>
</div>
</br>
<div class="table-responsive">
    <table class="table">
        <tr>
            <td class="info"><b>Taller</b></td>
            <td><b>Vehiculo</b></td>
            <td><b>Origen</b></td>
            <td><b>Fecha de ingreso</b></td>
            <td><b>Fecha de salida</b></td>
            <td><b>Problema</b></td>
            <td><b>Opciones</b></td>
        </tr>
        {% autopaginate m_list 20 %}
        {% for m in m_list %}
            {% if m.fixed %}
            <tr class="active" id="row_{{ m.id }}">
            {% else %}
            <tr class="danger" id="row_{{ m.id }}">
            {% endif %}
                <td class="info">{{ m.workshop }}</td>
                <td>{{ m.car.internal_number }}</td>
                <td>{{ m.register.branch_office }}</td>
                <td>{{ m.date_joined|date:"d/m/Y" }}</td>
                {% if m.fixed %}
                    <td>{{ m.date_out|date:"d/m/Y" }}</td>
                {% else %}
                <td> --- </td>
                {% endif %}
                <td>{{ m.problem_description }}</td>
                <td>
                    {% if user.is_admin %}
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            Opciones <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" role="menu">
                            <li>
                            <a href="{{m.get_absolute_url }}/view/">
                                    <span>Ver</span>
                                </a>
                            </li>
                        </ul>
                    </li>
                    {% else %}
                        ---
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
    </table>
</div>
{% paginate %}
{% endblock %}

maintenance/templates/maintenance_program.html
{% extends "base.html" %}

{% load i18n %}
{% load staticfiles %}}
{% load pagination_tags %}


{% block content %}
<h4>Mantenimientos Programados de Vehiculos</h4>
<div class="row">
    <div class="col-xs-4">
        <form method="GET"
                action="{% url 'search_maintenance_program' %}" 
                class="form-inline" role="form">{% csrf_token %}
            <input type='text'
                    id='id_car' name='car'
                    autocomplete='off'
                    class="form-control" placeholder="Interno de Vehiculo" />
            <button type='submit' class="btn btn-default">
                Buscar
            </button>
        </form>
    </div>
</div>
</br>
<div class="table-responsive">
    <table class="table">
        <tr>
            <td class="info"><b>Taller</b></td>
            <td><b>Vehiculo</b></td>
            <td><b>Ultimo mantenimiento</b></td>
            <td><b>Km</b></td>
            <td><b>Fecha programada</b></td>
            <td><b>Km programado</b></td>
            <td><b>Motivo</b></td>
            <td><b>Opciones</b></td>
        </tr>
        {% autopaginate mp_list 20 %}
        {% for m in mp_list %}
            {% if not m.is_closed %}
            <tr class="success" id="row_{{ m.id }}">
            {% else %}
            <tr class="active" id="row_{{ m.id }}">
            {% endif %}
                <td class="info">{{ m.workshop }}</td>
                <td>{{ m.car.internal_number }}</td>
                <td>{{ m.last_date_maintenance|date:"d/m/Y" }}</td>
                <td>{{ m.last_km_maintenance }}</td>
                <td>{{ m.next_date_maintenance|date:"d/m/Y" }}</td>
                <td>{{ m.next_km_maintenance }}</td>
                <td>{{ m.reason }}</td>
                <td>
                    {% if user.is_admin %}
                        {% if not m.is_closed %}
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                Opciones <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu" role="menu">
                                <li>
                                <a href="{{m.get_absolute_url }}/close/">
                                        <span>Cancelar</span>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        {% else %}
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                Opciones <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu" role="menu">
                                <li>
                                <a href="{{m.get_absolute_url }}/open/">
                                        <span>Habilitar</span>
                                    </a>
                                </li>
                            </ul>
                        </li>

                        {% endif %}
                    {% else %}
                        ---
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
    </table>
</div>
{% paginate %}
{% endblock %}

maintenance/templates/view_car_workshop.html
{% extends "base.html" %}

{% load i18n %}
{% load staticfiles %}}
{% load pagination_tags %}

{% block content %}
<h4>Taller: {{ workshop.workshop }}</h4>
<b>Numero interno del Vehiculo:</b> {{ workshop.car.internal_number }}</br>
<b>Placa del Vehiculo:</b> {{ workshop.car.license_plate }}</br>
<b>Fecha de ingreso:</b> {{ workshop.date_joined|date:"d/m/Y" }}</br>
<b>Problema:</b> {{ workshop.car.problem_description }}</br>
{% if workshop.fixed %}
<b>Fecha de salida:</b> {{ workshop.date_out|date:"d/m/Y" }}</br>
{% else %}
    {% if user.is_admin %}
    <a class="btn btn-warning"
    role="button"
    href="{{ workshop.get_absolute_url }}/fixed/">Sacar del taller</a>
    {% else %}
    <b>Fecha de salida:</b> Sigue en taller
    {% endif %}
{% endif %}

{% endblock %}

maintenance/templates/workshop.html
{% extends "base.html" %}

{% load i18n %}
{% load staticfiles %}}

{% block content %}
    <!-- a href="{% url "upload_car" %}">Cargar los vehiculos</a>
    <a href="{% url "load_car_to_office" %}">Cargar vehiculos a las sucursales</a>
    <a href="{% url "upload_ladders" %}">Cargar escaleras</a -->
    <h2>Talleres de la empresa</h2>
    <div class="row">
        {% if user.is_admin %}
        <div class="col-xs-2">
            <a class="btn btn-warning"
                href="{% url 'new_workshop' %}"
                role="button"><b>Nuevo Taller &raquo;</b>
            </a>
        </div>
        {% endif %}
    </div>
    <div class="row">
        {% for workshop in w_list %}
            {% if workshop.is_active %}
            <div class="col-md-4 ">
                <h2>{{ workshop.branchoffice.name }}</h2>
            {% else %}
            <div class="col-md-4 alert fade in alert-danger">
                <h2>{{ workshop.branchoffice.name }}</h2>
                <h4>Deshabilitado</h4>
            {% endif %}
                {% if workshop.description %}
                    <p>{{ workshop.description }}</p>
                {% else %}
                    <p>Taller sin descripcion</p>
                {% endif %}
                <p>
                    <a class="btn btn-primary"
                       href="{{ workshop.get_absolute_url }}/cars/"
                       role="button">Ver autos &raquo;
                    </a>
                    {% if user.is_admin %}
                        {% if workshop.is_active %}
                        <a class="btn btn-danger"
                        href="{{ workshop.get_absolute_url }}/disabled/"
                        role="button">Deshabilitar Taller &raquo;
                        </a>
                        {% else %}
                        <a class="btn btn-success"
                        href="{{ workshop.get_absolute_url }}/enabled/"
                        role="button">Habilitar Taller &raquo;
                        </a>
                        {% endif %}
                    {% endif %}
                </p>
        </div>
        {% endfor %}
    </div>
{% endblock %}